Node_filename: {
  Denmark: "./DK2020_2018edition.txt"
}
#The key is the year name output. First value in the list is the year name in the EMPIRE input database 
#and the second value is the year name in the EMPIRE output database.
#Example: "2020-2025": ["1", "2020-2025"]
Year_mapping: {
  "2020-2025": ["1", "2020-2025"]
}

RES: {
  RES1: {Wind onshore: ["Windonshore"]},
  RES2: {Solar: ["Solar"]},
  RES3: {Wind Offshore: ["Windoffshorefloating", "Windoffshoregrounded"]},
  RES4: {Hydro RoR: ["Hydrorun-of-the-river"]},
}

Condensing_PP: {
    Bio: ["Bio", "Bio10cofiring", "Bio10cofiring", "Bioexisting"],
    Coal: ["Coal","CoalCCS", "CoalCCSadv", "Coalexisting"],
    Gas: ["GasCCGT", "GasCCS", "GasCSSadv","Gasexsisting", "GasOCGT"],
    Geo: ["Geo"], #?
    Hydrogen: ["HydrogenCCGT", "Hydrogenfuelcell", "HydrogenOCGT"],
    Lignite: ["Ligniteexisting", "Lignite", "LigniteCCSadv", "LigniteCCSsup"], #?
    Oil: ["Oilexisting"],
    Waste: ["Waste"] # ?
}
Nuclear: ["Nuclear"]

Battery_storage: ["Li-Ion_BESS"]
HydroPump_storage: ["HydroPumpStorage"]