Node_filename: {
  Denmark: "./DK2020_2018edition.txt"
}
Country_key: {
  Denmark: "DK"
}
#The key is the yearname in the output file. First value in the list is the year name in the EMPIRE input database 
#and the second value is the year name in the EMPIRE output database.
#Example: "2020-2025": ["1", "2020-2025"]
Year_mapping: {
  "2025-2030": ["1", "2025-2030"]
}

# Get the empire timeseries directly from the data_handler
Timeseries_folder: "../InternalEMPIRE/Data handler/full_model/ScenarioData/"
Timeseries_year: "2015"

Hydrogen_ton_to_MWh: 0.0303

RES: {
  Wind: ["Windonshore"],
  Photo Voltaic: ["Solar"],
  Offshore Wind: ["Windoffshorefloating", "Windoffshoregrounded"],
  River Hydro: ["Hydrorun-of-the-river"],
  Wave Power: ["Wave"],
}

Condensing_PP: {
    Bio: ["Bio", "Bio10cofiring", "Bio10cofiring", "Bioexisting"],
    Coal: ["Coal","CoalCCS", "CoalCCSadv", "Coalexisting","Ligniteexisting", "Lignite", "LigniteCCSadv", "LigniteCCSsup"],
    Gas: ["GasCCGT", "GasCCS", "GasCSSadv","Gasexsisting", "GasOCGT"],
    Hydrogen: ["HydrogenCCGT", "Hydrogenfuelcell", "HydrogenOCGT"],
    Oil: ["Oilexisting"],
}
Nuclear: ["Nuclear"]
Geothermal: ["Geo"]
Waste: ["Waste"]

Hydro_prod: ["Hydroregulated"]
Hydro_stor: ["hydro_reg"]
Battery_storage: ["Li-Ion_BESS"]
HydroPump_storage: ["HydroPumpStorage"]