#This is the settings file for the integration between EMPIRE, EMX and ENERGYPLAN.

#The country_filename tells which countries are transferred and with which file.
Country_filename: {
  Denmark: "DK2020_2018edition.txt"
}
Years_modelled: ["2025-2030"]

#### settings for EMX results #####-------------------------------------------------------------------

#Map the periods EnergyPlan periods with EMX periods
Year_mapping_EMX: {
  "2025-2030": "sp1",
  "2030-2035": "sp2",
  "2035-2040": "sp3",
  "2040-2045": "sp4",
}

#Country codes, note that the EMX results are in NUTS3 level in here 
Country_codes_EMX: {"Denmark":"DK", "Norway": "NO", "Sweden":"SE", "Finland":"FI"}

#hydrogen infrastructure lifetime for EnergyPlan
hydrogen_infrastructure_lifetime: 30

# Mapping of result items to EnergyPlan items.
# Capacity is a sum and capex capacity weighted average
EMX_powerline: ["Powerline"]
EMX_H2_transport: ["H2_Road", "LH2_Road", "H2_Pipeline"]
EMX_H2_production: ["Hydrogen_OCGT", "SMR", "Hydrogen_fuel_cell", "Hydrogen_CCGT", "Electrolyzer"]
EMX_H2_storage: [H2_Storage]

#Here you can choose which parts are transferred from EMX to EnergyPlan
H2_transport_capacity: False
H2_transport_capex: True
H2_transport_fixed_om: True
H2_production_capacity: False
H2_production_capex: False
H2_production_fixed_om: False
H2_storage_capacity: False
H2_storage_capex: False
H2_storage_fixed_om: False
H2_storage_fixed_om_rate: 0.05  # For some reason this is not in EMX results

### settings for EMPIRE results ####-------------------------------------------------------------------

#The key is the yearname in the output file. First value in the list is the year name in the EMPIRE input database 
#and the second value is the year name in the EMPIRE output database.
#Example: "2020-2025": ["1", "2020-2025"]
Year_mapping: {
  "2025-2030": ["1", "2025-2030"]
}

#nodes of the countries in EMPIRE, if multiple nodes are present in EMPIRE for one country.
Country_nodes: {
  Denmark: ["Denmark", "Nordsøen"],
  Norway: ["NO1", "NO2", "NO3", "NO4", "NO5"],
  Sweden: ["Sweden"],
  Finland: ["Finland"],
}

#This is for handling timeseries .csv files where the country names are not the same as in EMPIRE
Node_key: {
  Denmark: "DK",
  NO1: "NO1",
  NO2: "NO2",
  NO3: "NO3",
  NO4: "NO4",
  NO5: "NO5"
}

# Weather year for timeseries data
Timeseries_year: "2015"

# Factor to multiply hydrogen tons to MWh
Hydrogen_ton_to_MWh: 0.0333

#Excluding connections with offshore nodes
Exclude_connections_to_nodes: ["EnergyhubEU", "Nordsøen", "SørligeNordsjøI", "SørligeNordsjøII", "UtsiraNord", "Sleipner"]

RES: {
  Wind: ["Windonshore"],
  Photo Voltaic: ["Solar"],
  Offshore Wind: ["Windoffshorefloating", "Windoffshoregrounded"],
  River Hydro: ["Hydrorun-of-the-river"],
  Wave Power: ["Wave"],
}

Condensing_PP: {
    Bio: ["Bio", "Bioexisting"],
    Coal: ["Bio10cofiring", "Bio10cofiringCSS","Coal","CoalCCS", "CoalCCSadv", "Coalexisting","Ligniteexisting", "Lignite", "LigniteCCSadv", "LigniteCCSsup"],
    Gas: ["BiomethaneCCGT", "BiomethaneOCGT", GasCCGT", "GasCCS", "GasCSSadv","Gasexsisting", "GasOCGT"],
}

Nuclear: ["Nuclear"]
Geothermal: ["Geo"]
Waste: ["Waste"]

Hydro_prod: ["Hydroregulated"]
Hydro_stor: ["hydro_reg"]
Battery_storage: ["Li-Ion_BESS"]
HydroPump_storage: ["HydroPumpStorage"]

#All of this goes to PP2 in ENERGYPLAN
Only_power_production: {
    Hydrogen: ["HydrogenCCGT", "Hydrogenfuelcell", "HydrogenOCGT"],
    Oil: ["Oilexisting"],
}

#Rest goes to PP1 in ENERGYPLAN
Share of Condensing_PP_to_PP2: {
    Denmark: 0.3,
    Norway, 1.0
}

Share of condensing_PP1_in_CHP3: {
    Denmark: 0.7,
    Norway: 0.0
}


#The integration writes over the parameters of the ENERGYPLAN input file.
#Here you can set which parameters are gotten from EMPIRE and which are kept as in the original ENERGYPLAN input file.
Demand: True
DemandProfile: True
IndustrialDemand: True
HydrogenDemand: True
RESCapacityFactorProfile: True
HydroStorage: True
CO2Price: True

CAPEX: True
FOM: True
Lifetime: True
VOM: True
Efficiency: True

StorageCAPEX: True
StorageFOM: True
StorageLifetime: True
StorageVOM: True
StorageEfficiency: True

InterconnectionInvestment: True

ResultsCapacity: True
ResultsTransmissionCapacity: True
ResultsStorageCapacity: True
ResultsHydroCapacity: True
ResultsHydrogenStorageCapacity: True
ResultsElectrolyzerCapacity: True

SharesOfCondensingFuelTypes: True
SharesOfPP2FuelTypes: True

ElectrolyzerEfficiency: True
HydrogenImport: True
